# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-rdoc_rails}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chinasaur", "George 'Jake' Wendt"]
  s.date = %q{2011-01-19}
  s.description = %q{longer description of your gem}
  s.email = %q{github@jakewendt.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/rdoc_rails.rb",
    "lib/rdoc_rails/rake.rb",
    "lib/rdoc_rails/rdoc/ar_association.rb",
    "lib/rdoc_rails/rdoc/context.rb",
    "lib/rdoc_rails/rdoc/generator/railsfish.rb",
    "lib/rdoc_rails/rdoc/generator/template/railsfish/classpage.rhtml",
    "lib/rdoc_rails/rdoc/parser/rails.rb",
    "lib/rdoc_rails/rdoc/token_stream.rb",
    "lib/tasks/rdoc_rails.rake"
  ]
  s.homepage = %q{http://github.com/jakewendt/rdoc_rails}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/app/models/blog.rb",
    "test/app/models/comment.rb",
    "test/app/models/post.rb",
    "test/app/models/user.rb",
    "test/rdoc_rails_test.rb",
    "test/tasks/testing.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 2"])
      s.add_runtime_dependency(%q<rdoc>, ["~> 2"])
    else
      s.add_dependency(%q<rails>, ["~> 2"])
      s.add_dependency(%q<rdoc>, ["~> 2"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 2"])
    s.add_dependency(%q<rdoc>, ["~> 2"])
  end
end

